#!/bin/bash

# Check privileges
user=$(id -u)
if [[ ${user} -ne 0 ]]; then
  echo "Please run as root"
  exit 1
fi

########## Start utility functions
bordered_title() {
  title="| $1 |"
  edge="${title//./-}"
  echo "${edge}"
  echo "${title}"
  echo "${edge}"
}

# concat $2 $1 times and print
repeated_char() {
  printf "%$1s" | tr " " "$2"
}

# print ce_alue
print_ce_alue() {
  alue=/opt/zextras/.mini_alue_ce
  if [[ -e "${alue}" ]]; then
    repeated_char 80 "-"
    echo
    fold -w 80 -s "${alue}"
    repeated_char 80 "-"
    echo $'\n'
  fi
}

########## End utility functions

########## Start Carbonio Bootstrap

if [[ -z "$1" ]] || [[ "$1" = "-c" ]]; then
  # print welcome message
  bordered_title $'Starting Carbonio Bootstrap...'

  # print product usage information
  print_ce_alue
fi

# Bootstrap and start C services
/opt/zextras/libexec/zmsetup.pl "${@}"

# Fix permission after services starting
/opt/zextras/libexec/zmfixperms

########## End Carbonio Bootstrap
